version: "3.8"
services:
  model-cluster-ip-service:
    image: models/tfs_resnet
    build: 
      dockerfile: resnet_server.dockerfile
    ports:
      - '8501:8501'
  web:
    image: frontend/flaskweb
    build:
      context: ./frontend/
      dockerfile: ../flaskweb.dockerfile
    ports:
      - '8080:8080'