apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: beingme97/cs237-resnet-server:1.0
          ports:
            - containerPort: 8501
          imagePullPolicy: Always
          env:
            - name: MODEL_NAME
              value: "resnet_classification"
