apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: resnetalt
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: resnetalt
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 50