apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-web
spec:
  replicas: 1
  selector:
    matchLabels:
      component: flask-web
  template:
    metadata:
      labels:
        component: flask-web
    spec:
      containers:
        - name: flask-web
          image: beingme97/cs237-flask-web:1.0
          resources:
            requests:
              memory: "1024Mi"
              cpu: "500m"
            limits:
              memory: "2048Mi"
              cpu: "1000m"
          ports:
            - containerPort: 8080
          imagePullPolicy: Always