apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: flask-web
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flask-web
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 90